-- Recordatorios de impago y textos de las plantillas.

-- 1) Segundo recordatorio de impago: el calendario tenía dos pasos
--    `email_reminder` (días 1 y 7) y el índice único por tipo descartaba el
--    segundo, así que nunca se enviaba. Tiene ahora su propio tipo.
ALTER TYPE "dunning_action_type" ADD VALUE IF NOT EXISTS 'email_reminder_final';

-- 2) Primer recordatorio sin editar: texto nuevo con el enlace para pagar
--    (texto y HTML, solo si nadie la ha editado).
UPDATE "message_templates" SET "body_text" = E'Hola {{customer.firstName}},\n\nLa factura {{invoice.number}} venció el {{invoice.dueDate}} y tiene {{invoice.amountPending}} pendientes. Puede que se te haya pasado: puedes pagarla ahora desde tu área de clientes:\n\n{{portal.url}}\n\nSi ya la has pagado, ignora este mensaje.\n\nUn saludo,\nEl equipo de {{tenant.name}}', "body_html" = E'<!DOCTYPE html><html lang="es"><body style="font-family:Inter,system-ui,sans-serif;color:#111;max-width:560px;margin:0 auto;padding:24px;">\n<h2 style="margin-top:0">Factura pendiente</h2>\n<p>Hola {{customer.firstName}},</p><p>La factura <strong>{{invoice.number}}</strong> venció el {{invoice.dueDate}} y tiene <strong>{{invoice.amountPending}}</strong> pendientes. Puede que se te haya pasado: puedes pagarla ahora desde tu área de clientes.</p><p><a href="{{portal.url}}" style="display:inline-block;padding:10px 18px;background:#111;color:#fff;border-radius:8px;text-decoration:none">Pagar ahora</a></p><p>Si ya la has pagado, ignora este mensaje.</p>\n<hr style="margin:24px 0;border:none;border-top:1px solid #eee" />\n<p style="font-size:12px;color:#888;">Enviado por {{tenant.name}}.</p>\n</body></html>'
WHERE "code" = 'invoice_overdue_email' AND "body_text" = E'Hola {{customer.firstName}},\n\nTienes pendiente la factura {{invoice.number}} ({{invoice.amountPending}} EUR). Llevamos {{invoice.daysOverdue}} dias de demora.\n\nPor favor, regulariza el pago lo antes posible.\n\nGracias,\nEl equipo de {{tenant.name}}';

-- 3) Las variables de importe ya llevan el símbolo («121,00 €»): se quita el
--    « EUR» que añadían las plantillas, también en las editadas (sustituir
--    `{{variable}} EUR` es seguro). Y tildes de los textos por defecto.
UPDATE "message_templates" SET "subject" = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE("subject", '{{invoice.total}} EUR', '{{invoice.total}}'), '{{invoice.amountPending}} EUR', '{{invoice.amountPending}}'), '{{contract.priceMonthly}} EUR', '{{contract.priceMonthly}}'), 'ya esta lista', 'ya está lista'), 'factura esta lista', 'factura está lista'), '}} esta activo', '}} está activo'), 'dias de demora', 'días de demora'), 'dias</strong> de demora', 'días</strong> de demora'), 'Nos encantaria conocer tu opinion', 'Nos encantaría conocer tu opinión'), 'te llevara un minuto', 'te llevará un minuto'), 'Dejar mi valoracion', 'Dejar mi valoración'), '¿Que tal', '¿Qué tal') WHERE "subject" IS NOT NULL;
UPDATE "message_templates" SET "body_text" = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE("body_text", '{{invoice.total}} EUR', '{{invoice.total}}'), '{{invoice.amountPending}} EUR', '{{invoice.amountPending}}'), '{{contract.priceMonthly}} EUR', '{{contract.priceMonthly}}'), 'ya esta lista', 'ya está lista'), 'factura esta lista', 'factura está lista'), '}} esta activo', '}} está activo'), 'dias de demora', 'días de demora'), 'dias</strong> de demora', 'días</strong> de demora'), 'Nos encantaria conocer tu opinion', 'Nos encantaría conocer tu opinión'), 'te llevara un minuto', 'te llevará un minuto'), 'Dejar mi valoracion', 'Dejar mi valoración'), '¿Que tal', '¿Qué tal') WHERE "body_text" IS NOT NULL;
UPDATE "message_templates" SET "body_html" = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE("body_html", '{{invoice.total}} EUR', '{{invoice.total}}'), '{{invoice.amountPending}} EUR', '{{invoice.amountPending}}'), '{{contract.priceMonthly}} EUR', '{{contract.priceMonthly}}'), 'ya esta lista', 'ya está lista'), 'factura esta lista', 'factura está lista'), '}} esta activo', '}} está activo'), 'dias de demora', 'días de demora'), 'dias</strong> de demora', 'días</strong> de demora'), 'Nos encantaria conocer tu opinion', 'Nos encantaría conocer tu opinión'), 'te llevara un minuto', 'te llevará un minuto'), 'Dejar mi valoracion', 'Dejar mi valoración'), '¿Que tal', '¿Qué tal') WHERE "body_html" IS NOT NULL;
